ui:
  build: ./ui
  working_dir: /ui  
  expose:
    - 8002
  links:
    - db  
  volumes:
    - ./ui:/ui    
    - ./data/file:/data
    - /etc/localtime:/etc/localtime:ro   
  command: /usr/local/bin/gunicorn -w 2 -b :8002 server:app 

nginx:
  restart: always
  build: ./nginx
  ports:
    - 80:80      
  volumes:
    - /etc/timezone:/etc/timezone
    - /etc/localtime:/etc/localtime:ro     
  links:
    - ui
    - api

db:
  image: mongo:latest    
  volumes:
    - ./data/db:/data/db  


