main:
  image: nginx
  volumes:
    - ./server/conf.d/:/etc/nginx/conf.d
    - /etc/localtime:/etc/localtime:ro
    - ./server/proxy/html:/usr/share/nginx/html:rw
  environment:
    - VIRTUAL_HOST=fbcredibility.com
    - LETSENCRYPT_HOST=fbcredibility.com
    - LETSENCRYPT_EMAIL=chaluemwut@hotmail.com

ui:
  build: ./ui
  working_dir: /ui  
  expose:
    - 8003
  links:
    - db  
  volumes:
    - ./ui:/ui    
    - ./data:/data
    - /etc/localtime:/etc/localtime:ro   
  command: /usr/local/bin/gunicorn -w 2 -b :8003 server:app 

nginx:
  image: nginx
  ports:
    - 80:80
    - 443:443
  links:
    - ui:ui  
  volumes:
    - /etc/nginx/conf.d
    - /etc/nginx/vhost.d
    - ./server/proxy/html:/usr/share/nginx/html:ro
    - ./server/proxy/certs:/etc/nginx/certs:ro
    - /etc/localtime:/etc/localtime:ro

db:
  image: mongo:latest    
  volumes:
    - /home/ubuntu/datafile/data/db:/data/db
    - /etc/timezone:/etc/timezone
    - /etc/localtime:/etc/localtime:ro 

nginx-gen:
  image: jwilder/docker-gen
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - ./server/proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
  volumes_from:
    - nginx
  entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

letsencrypt-nginx-proxy-companion:
  image: alastaircoote/docker-letsencrypt-nginx-proxy-companion
  volumes_from:
    - nginx
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - ./server/proxy/certs:/etc/nginx/certs:rw
    - /etc/localtime:/etc/localtime:ro    
  environment:
    - NGINX_DOCKER_GEN_CONTAINER=nginx-gen